# Generated by Django 3.1.3 on 2020-11-29 13:09

from django.db import migrations, models
import ml_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestmodel',
            name='file',
            field=models.FileField(upload_to=ml_api.models.media_file_name),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=ml_api.models.media_file_name),
        ),
    ]
